#!/bin/bash
# =============================================================================
# ArbitrageExecutorYul.sol - Arbitrum Sepolia Testnet Deployment Script
# =============================================================================
# Usage: ./deploy.sh
# Requirements: 
#   - Foundry (forge) installed: https://getfoundry.sh
#   - Alchemy or Infura API key for Arbitrum Sepolia
#   - Testnet ETH in wallet
# =============================================================================

set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# RPC URLs (Public - no API key required for Sepolia)
export ARBITRUM_SEPOLIA_RPC="${ARBITRUM_SEPOLIA_RPC:-https://sepolia-rollup.arbitrum.io/rpc}"
export RPC_URL="$ARBITRUM_SEPOLIA_RPC"

# Chain ID for Arbitrum Sepolia
CHAIN_ID=421614

# Contract configuration
CONTRACT_NAME="ArbitrageExecutorYul"
MIN_PROFIT_WEI="1000000000000000"  # 0.001 ETH minimum profit

# ─────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ─────────────────────────────────────────────────────────────────────────────

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_dependencies() {
    log_info "Checking dependencies..."
    
    # Check for forge
    if ! command -v forge &> /dev/null; then
        log_error "forge not found. Install Foundry: https://getfoundry.sh"
        exit 1
    fi
    
    # Check for cast
    if ! command -v cast &> /dev/null; then
        log_error "cast not found. Install Foundry: https://getfoundry.sh"
        exit 1
    fi
    
    # Check for PRIVATE_KEY
    if [[ -z "${PRIVATE_KEY:-}" ]]; then
        if [[ -f ".env" ]]; then
            source .env
        fi
    fi
    
    if [[ -z "${PRIVATE_KEY:-}" ]]; then
        log_error "PRIVATE_KEY not set. Set via environment variable or .env file"
        log_info "Example: export PRIVATE_KEY=0xYour64HexKey"
        exit 1
    fi
    
    log_info "All dependencies satisfied"
}

compile_contracts() {
    log_info "Compiling contracts..."
    
    # Create lib directory for Solidity dependencies if needed
    mkdir -p lib
    
    # Download Uniswap V3 interfaces if not present
    if [[ ! -d "lib/v3-periphery" ]]; then
        log_info "Cloning Uniswap V3 periphery..."
        git clone https://github.com/Uniswap/v3-periphery.git lib/v3-periphery --depth 1 2>/dev/null || true
    fi
    
    # Compile with Forge
    forge build --force --optimizer-runs 200
    
    log_info "Compilation successful"
}

deploy_contract() {
    log_info "Deploying to Arbitrum Sepolia..."
    log_info "RPC: $ARBITRUM_SEPOLIA_RPC"
    log_info "Chain ID: $CHAIN_ID"
    
    # Deploy the contract
    DEPLOY_OUTPUT=$(forge create --rpc-url "$ARBITRUM_SEPOLIA_RPC" \
        --chain-id "$CHAIN_ID" \
        --private-key "$PRIVATE_KEY" \
        src/contracts/ArbitrageExecutorYul.sol:ArbitrageExecutorYul \
        --constructor-args "$MIN_PROFIT_WEI" \
        2>&1)
    
    # Extract deployed address
    CONTRACT_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep "Deployed to:" | awk '{print $3}')
    
    if [[ -z "$CONTRACT_ADDRESS" ]]; then
        log_error "Deployment failed. Output:"
        echo "$DEPLOY_OUTPUT"
        exit 1
    fi
    
    log_info "Contract deployed successfully!"
    log_info "Contract Address: $CONTRACT_ADDRESS"
    
    # Verify deployment
    log_info "Verifying deployment..."
    DEPLOYED_CODE=$(cast code "$CONTRACT_ADDRESS" --rpc-url "$ARBITRUM_SEPOLIA_RPC")
    
    if [[ ${#DEPLOYED_CODE} -gt 2 ]]; then
        log_info "Contract verified on-chain (code length: ${#DEPLOYED_CODE} bytes)"
    else
        log_warn "Contract code not found on-chain"
    fi
    
    echo "$CONTRACT_ADDRESS"
}

create_env_file() {
    local CONTRACT_ADDRESS="$1"
    
    log_info "Creating .env.testnet configuration..."
    
    cat > .env.testnet << EOF
# =============================================================================
# Arbitrum Sepolia Testnet Configuration
# Generated by deploy.sh
# =============================================================================

# ─────────────────────────────────────────────────────────────────────────────
# CHAIN CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────
CHAIN_ID=$CHAIN_ID
ARBITRUM_RPC_URL=$ARBITRUM_SEPOLIA_RPC
ARBITRUM_WS_URL=wss://sepolia-rollup.arbitrum.io/ws

# ─────────────────────────────────────────────────────────────────────────────
# CONTRACT ADDRESSES
# ─────────────────────────────────────────────────────────────────────────────
CONTRACT_ADDRESS=$CONTRACT_ADDRESS

# ─────────────────────────────────────────────────────────────────────────────
# PRIVATE KEYS (DO NOT COMMIT!)
# ─────────────────────────────────────────────────────────────────────────────
# PRIVATE_KEY is read from environment or .env file

# ─────────────────────────────────────────────────────────────────────────────
# ENGINE CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────
SHADOW_MODE=true
USE_MEV_PROTECTION=false
RUST_LOG=info
RUST_BACKTRACE=1

# ─────────────────────────────────────────────────────────────────────────────
# PRIVATE RPCS (not used in testnet mode)
# ─────────────────────────────────────────────────────────────────────────────
# PRIVATE_RPC_URL=
PRIVATE_RPC_FALLBACK=bloxroute,flashbots,mevblocker

# ─────────────────────────────────────────────────────────────────────────────
# BROADCASTER
# ─────────────────────────────────────────────────────────────────────────────
ARBITRUM_BROADCAST_RPC=$ARBITRUM_SEPOLIA_RPC

# ─────────────────────────────────────────────────────────────────────────────
# PERFORMANCE TUNING
# ─────────────────────────────────────────────────────────────────────────────
# CPU cores for pinning (adjust based on your machine)
WS_CORE=2
SIM_CORE=3

# ─────────────────────────────────────────────────────────────────────────────
# CONTRACT PARAMETERS
# ─────────────────────────────────────────────────────────────────────────────
MIN_PROFIT_WEI=$MIN_PROFIT_WEI
EOF
    
    log_info ".env.testnet created successfully"
}

display_faucet_info() {
    echo ""
    echo "================================================================================"
    echo "                    ARBITRUM SEPOLIA TESTNET INFO"
    echo "================================================================================"
    echo ""
    echo "Faucets to get testnet ETH:"
    echo "  1. Alchemy Faucet: https://www.alchemy.com/faucets/arbitrum-sepolia"
    echo "  2. QuickNode Faucet: https://faucet.quicknode.com/arbitrum/sepolia"
    echo "  3. Discord Faucet: https://discord.gg/arbitrum"
    echo ""
    echo "Block Explorer:"
    echo "  - Arbitrum Sepolia Explorer: https://sepolia.arbiscan.io"
    echo ""
    echo "================================================================================"
}

# ─────────────────────────────────────────────────────────────────────────────
# MAIN EXECUTION
# ─────────────────────────────────────────────────────────────────────────────

main() {
    echo ""
    echo "================================================================================"
    echo "     ARBITRAGE EXECUTOR YUL - ARBITRUM SEPOLIA DEPLOYMENT"
    echo "================================================================================"
    echo ""
    
    # Check environment
    check_dependencies
    
    # Compile contracts
    compile_contracts
    
    # Deploy contract
    CONTRACT_ADDRESS=$(deploy_contract)
    
    # Create .env.testnet
    create_env_file "$CONTRACT_ADDRESS"
    
    # Show faucet info
    display_faucet_info
    
    echo ""
    log_info "Deployment complete!"
    echo ""
    echo "Next steps:"
    echo "  1. Get testnet ETH from a faucet above"
    echo "  2. Run: source .env.testnet && ./run_testnet.sh"
    echo ""
}

main "$@"
