@echo off
REM =============================================================================
REM ArbitrageExecutorYul.sol - Arbitrum Sepolia Deployment Script (Windows)
REM =============================================================================
REM Requirements:
REM   - Foundry (forge) installed: https://getfoundry.sh
REM   - Anvil RPC URL for Arbitrum Sepolia
REM   - Testnet ETH in wallet
REM =============================================================================

setlocal enabledelayedexpansion

echo.
echo =============================================================================
echo      ARBITRAGE EXECUTOR YUL - ARBITRUM SEPOLIA DEPLOYMENT
echo =============================================================================
echo.

set PROJECT_ROOT=%~dp0
set ARBITRUM_SEPOLIA_RPC=https://sepolia-rollup.arbitrum.io/rpc
set CHAIN_ID=421614
set MIN_PROFIT_WEI=1000000000000000

echo [INFO] Checking dependencies...
echo.

where forge >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo [ERROR] forge not found. Install Foundry: https://getfoundry.sh
    exit /b 1
)

where cast >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo [ERROR] cast not found. Install Foundry: https://getfoundry.sh
    exit /b 1
)

if "%PRIVATE_KEY%"=="" (
    echo [ERROR] PRIVATE_KEY not set.
    echo Set via: set PRIVATE_KEY=0xYour64HexKey
    exit /b 1
)

echo [INFO] All dependencies satisfied
echo.

REM Build contracts
echo [INFO] Building contracts...
call forge build --force --optimizer-runs 200 2>nul

if %ERRORLEVEL% neq 0 (
    echo [ERROR] Contract compilation failed
    exit /b 1
)

echo [OK] Contracts compiled successfully
echo.

REM Deploy contract
echo [INFO] Deploying to Arbitrum Sepolia...
echo        RPC: %ARBITRUM_SEPOLIA_RPC%
echo        Chain ID: %CHAIN_ID%
echo.

set DEPLOY_OUTPUT=
for /f "tokens=*" %%i in ('forge create --rpc-url "%ARBITRUM_SEPOLIA_RPC%" --chain-id %CHAIN_ID% --private-key %PRIVATE_KEY% src\contracts\ArbitrageExecutorYul.sol:ArbitrageExecutorYul --constructor-args %MIN_PROFIT_WEI% 2^>^&1') do (
    set DEPLOY_OUTPUT=!DEPLOY_OUTPUT!%%i
)

echo %DEPLOY_OUTPUT%
echo.

REM Extract contract address
set CONTRACT_ADDRESS=
echo %DEPLOY_OUTPUT% | findstr /C:"Deployed to:" >nul
if %ERRORLEVEL% equ 0 (
    for /f "tokens=3" %%a in ('echo %DEPLOY_OUTPUT% ^| findstr "Deployed to:"') do (
        set CONTRACT_ADDRESS=%%a
    )
)

if "%CONTRACT_ADDRESS%"=="" (
    echo [ERROR] Deployment failed - no contract address found
    exit /b 1
)

echo [OK] Contract deployed successfully!
echo [OK] Contract Address: %CONTRACT_ADDRESS%
echo.

REM Create .env.testnet
echo [INFO] Creating .env.testnet...

(
    echo # =============================================================================
    echo # Arbitrum Sepolia Testnet Configuration
    echo # Generated by deploy.ps1
    echo # =============================================================================
    echo.
    echo CHAIN_ID=%CHAIN_ID%
    echo ARBITRUM_RPC_URL=%ARBITRUM_SEPOLIA_RPC%
    echo ARBITRUM_WS_URL=wss://sepolia-rollup.arbitrum.io/ws
    echo.
    echo CONTRACT_ADDRESS=%CONTRACT_ADDRESS%
    echo.
    echo SHADOW_MODE=true
    echo USE_MEV_PROTECTION=false
    echo RUST_LOG=info
    echo.
    echo ARBITRUM_BROADCAST_RPC=%ARBITRUM_SEPOLIA_RPC%
    echo.
    echo WS_CORE=2
    echo SIM_CORE=3
    echo.
    echo TELEMETRY_PORT=3000
    echo MIN_PROFIT_WEI=%MIN_PROFIT_WEI%
) > .env.testnet

echo [OK] .env.testnet created
echo.

REM Verify deployment
echo [INFO] Verifying deployment on-chain...
cast call %CONTRACT_ADDRESS% "minProfit()" --rpc-url %ARBITRUM_SEPOLIA_RPC% 2>nul
if %ERRORLEVEL% equ 0 (
    echo [OK] Contract verified on-chain
) else (
    echo [WARN] Could not verify contract - check explorer manually
)

echo.
echo =============================================================================
echo                     DEPLOYMENT COMPLETE
echo =============================================================================
echo.
echo Contract Address: %CONTRACT_ADDRESS%
echo.
echo Next steps:
echo   1. Get testnet ETH: https://www.alchemy.com/faucets/arbitrum-sepolia
echo   2. Run: .\.run_testnet.ps1
echo.

endlocal
