// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title ArbitrageExecutorTwoLeg
/// @notice Two-leg arbitrage executor with Balancer V2 flash loan
/// @dev Supports: TokenA -> DEX1 -> TokenB -> DEX2 -> TokenA
///
/// ## Router ABI (AUDIT #4)
///
/// The executor calls Uniswap **SwapRouter02**
/// (`0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45`) using the struct-based
/// `exactInputSingle`:
///
/// ```text
/// exactInputSingle((address,address,uint24,address,uint256,uint256,uint160))
/// selector = 0x04e45aaf
/// ```
///
/// The struct has **7 fields — there is NO deadline field** (deadlines were
/// removed from SwapRouter02). Calldata layout (260 bytes):
///
/// ```text
/// [0..4]      selector  0x04e45aaf
/// [4..36]     0x20      offset to the struct
/// [36..68]    tokenIn
/// [68..100]   tokenOut
/// [100..132]  fee           (uint24, right-aligned in the word)
/// [132..164]  recipient     (address, left-padded)
/// [164..196]  amountIn
/// [196..228]  amountOutMinimum
/// [228..260]  sqrtPriceLimitX96 (0 = no limit)
/// ```
///
/// ## Net profit accounting (AUDIT #5)
///
/// `execute()` snapshots the loan-token balance BEFORE the flash loan and
/// stores it inside `userData`. Profit is computed inside the callback as
///
///     profit = balAfter - balanceBefore - repayment
///
/// so any pre-existing executor token balance is excluded: only tokens
/// generated by leg1+leg2 during THIS execution count as profit.
/// The profit is persisted in `lastProfit` storage and returned to the
/// caller by `execute()`.
interface IUniswapV3Factory {
    function getPool(address tokenA, address tokenB, uint24 fee) external view returns (address pool);
}

interface IAllowanceTransfer {
    function approve(address token, address spender, uint160 amount, uint48 expiration) external;
}

contract ArbitrageExecutorTwoLeg {
    /// @notice Balancer V2 Vault
    address constant BALANCER_VAULT = 0xBA12222222228d8Ba445958a75a0704d566BF2C8;

    /// @notice Uniswap V3 SwapRouter02
    address constant UNISWAP_V3_ROUTER = 0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45;

    /// @notice Uniswap V3 Factory
    address constant UNISWAP_V3_FACTORY = 0x1F98431c8aD98523631AE4a59f267346ea31F984;

    /// @notice Uniswap V3 Permit2
    address constant PERMIT2 = 0x000000000022D473030F116dDEE9F6B43aC78BA3;

    /// @notice Minimum profit threshold (loan-token raw units)
    uint256 public minProfit;

    /// @notice Owner
    address public owner;

    /// @notice Net profit of the most recent successful execution
    /// (excludes pre-existing balances, flash-loan principal and fees)
    uint256 public lastProfit;

    /// @notice Reentrancy lock
    uint256 private _locked;

    /// @notice Reentrancy guard
    modifier nonReentrant() {
        require(_locked == 0, "REENTRANCY");
        _locked = 1;
        _;
        _locked = 0;
    }

    /// @notice Arbitrage profit event
    event Profit(uint256 profit, uint256 gasLeft);

    /// @notice Flash loan received
    event LoanReceived(address token, uint256 amount, uint256 fee);

    constructor(uint256 _minProfit) {
        owner = msg.sender;
        minProfit = _minProfit;
        assembly { sstore(minProfit.slot, _minProfit) }
    }

    modifier onlyOwner() {
        assembly { if iszero(eq(caller(), sload(owner.slot))) { revert(0, 0) } }
        _;
    }

    receive() external payable {}

    function setMinProfit(uint256 _minProfit) external onlyOwner {
        assembly { sstore(minProfit.slot, _minProfit) }
    }

    /// @notice Entry point - executes two-leg arbitrage via Balancer flash loan
    /// @param loanToken Token to borrow
    /// @param loanAmount Amount to borrow
    /// @param leg1Pool Pool for first swap (TokenA -> TokenB)
    /// @param leg2Pool Pool for second swap (TokenB -> TokenA)
    /// @param leg1Data Encoded first swap parameters (router calldata)
    /// @param leg2Data Encoded second swap parameters (router calldata)
    /// @return profit Net profit in loan-token raw units (balanceBefore-adjusted)
    function execute(
        address loanToken,
        uint256 loanAmount,
        address leg1Pool,
        address leg2Pool,
        bytes calldata leg1Data,
        bytes calldata leg2Data
    ) external nonReentrant returns (uint256 profit) {
        require(leg1Pool != address(0), "INVALID_LEG1_POOL");
        require(leg2Pool != address(0), "INVALID_LEG2_POOL");

        // AUDIT #5: snapshot BEFORE borrowing. Any pre-existing balance of
        // loanToken held by this executor is recorded here and subtracted
        // from the final accounting, so it can never be counted as profit.
        uint256 balanceBefore = IERC20(loanToken).balanceOf(address(this));

        bytes memory userData = abi.encode(
            msg.sender, // initiator (AUDIT #6 fix)
            loanToken,
            loanAmount,
            leg1Pool,
            leg2Pool,
            leg1Data,
            leg2Data,
            balanceBefore
        );

        IERC20[] memory tokens = new IERC20[](1);
        tokens[0] = IERC20(loanToken);
        uint256[] memory amounts = new uint256[](1);
        amounts[0] = loanAmount;

        (bool success, bytes memory returnData) = BALANCER_VAULT.call(
            abi.encodeWithSelector(
                bytes4(keccak256("flashLoan(address,address[],uint256[],bytes)")),
                address(this),
                tokens,
                amounts,
                userData
            )
        );

        if (!success) revert(_getRevertReason(returnData));

        // Profit is written by the callback (atomic with the flash loan).
        profit = lastProfit;
    }

    /// @notice Balancer callback - executes two-leg arbitrage
    /// @dev Called by Balancer Vault after sending the flash loan
    function receiveFlashLoan(
        address[] calldata tokens,
        uint256[] calldata amounts,
        uint256[] calldata feeAmounts,
        bytes calldata userData
    ) external {
        // ═══════════════════════════════════════════════════════════════
        // GUARD: Verify caller is Balancer Vault
        // ═══════════════════════════════════════════════════════════════
        require(msg.sender == BALANCER_VAULT, "ONLY_BALANCER");

        // ═══════════════════════════════════════════════════════════════
        // DECODE USERDATA (8 fields incl. balanceBefore)
        // ═══════════════════════════════════════════════════════════════
        address initiator;
        address loanToken;
        uint256 loanAmount;
        address leg1Pool;
        address leg2Pool;
        bytes memory leg1Data;
        bytes memory leg2Data;
        uint256 balanceBefore;

        (initiator, loanToken, loanAmount, leg1Pool, leg2Pool, leg1Data, leg2Data, balanceBefore) =
            abi.decode(userData, (address, address, uint256, address, address, bytes, bytes, uint256));

        // ═══════════════════════════════════════════════════════════════
        // VALIDATE TOKENS AND AMOUNTS
        // ═══════════════════════════════════════════════════════════════
        require(tokens.length == 1, "INVALID_TOKENS_LENGTH");
        require(amounts.length == 1, "INVALID_AMOUNTS_LENGTH");
        require(feeAmounts.length == 1, "INVALID_FEE_LENGTH");
        require(tokens[0] == loanToken, "TOKEN_MISMATCH");
        require(amounts[0] == loanAmount, "AMOUNT_MISMATCH");

        uint256 feeAmount = feeAmounts[0];
        uint256 repayment = loanAmount + feeAmount;

        // ═══════════════════════════════════════════════════════════════
        // VALIDATE ROUTE CALLDATA BEFORE EXECUTION
        // ═══════════════════════════════════════════════════════════════
        address leg1OutputToken = _validateAndDecodeLeg1(leg1Data, loanToken, loanAmount, leg1Pool);
        _validateAndDecodeLeg2(leg2Data, leg1OutputToken, leg2Pool);

        // ═══════════════════════════════════════════════════════════════
        // APPROVE ROUTER AND PERMIT2 FOR LOAN TOKEN
        // ═══════════════════════════════════════════════════════════════
        IERC20(loanToken).approve(UNISWAP_V3_ROUTER, type(uint256).max);
        IERC20(loanToken).approve(PERMIT2, type(uint256).max);
        IAllowanceTransfer(PERMIT2).approve(loanToken, UNISWAP_V3_ROUTER, type(uint160).max, type(uint48).max);

        // ═══════════════════════════════════════════════════════════════
        // LEG 1: loanToken -> intermediate via SwapRouter02
        // leg1Data is pre-encoded exactInputSingle calldata (struct form).
        // amountIn is validated on-chain to equal the flash-loan amount.
        // ═══════════════════════════════════════════════════════════════
        uint256 preExistingIntermediateBalance = IERC20(leg1OutputToken).balanceOf(address(this));
        
        (bool leg1Success,) = UNISWAP_V3_ROUTER.call(leg1Data);
        require(leg1Success, "LEG1_FAILED");

        uint256 postLeg1Balance = IERC20(leg1OutputToken).balanceOf(address(this));
        require(postLeg1Balance > preExistingIntermediateBalance, "LEG1_NO_OUTPUT");
        uint256 leg1Output = postLeg1Balance - preExistingIntermediateBalance;

        // ═══════════════════════════════════════════════════════════════
        // LEG 2: intermediate -> loanToken via SwapRouter02
        // The router consumes EXACTLY the leg1 output tokens (AUDIT #5 fix).
        // ═══════════════════════════════════════════════════════════════
        bytes memory leg2Calldata = _overrideAmountIn(leg2Data, leg1Output);

        IERC20(leg1OutputToken).approve(UNISWAP_V3_ROUTER, type(uint256).max);
        IERC20(leg1OutputToken).approve(PERMIT2, type(uint256).max);
        IAllowanceTransfer(PERMIT2).approve(leg1OutputToken, UNISWAP_V3_ROUTER, type(uint160).max, type(uint48).max);

        (bool leg2Success,) = UNISWAP_V3_ROUTER.call(leg2Calldata);
        require(leg2Success, "LEG2_FAILED");

        // ═══════════════════════════════════════════════════════════════
        // NET PROFIT (AUDIT #5): exclude pre-existing balances
        // ═══════════════════════════════════════════════════════════════
        uint256 balAfter = IERC20(loanToken).balanceOf(address(this));
        require(balAfter >= balanceBefore + repayment, "INSUFFICIENT_BALANCE");

        uint256 profit = balAfter - balanceBefore - repayment;
        require(profit >= minProfit, "PROFIT_TOO_LOW");

        // Persist so execute() can return it after the vault call unwinds.
        assembly { sstore(lastProfit.slot, profit) }

        // ═══════════════════════════════════════════════════════════════
        // REPAY FLASH LOAN: principal + fee
        // ═══════════════════════════════════════════════════════════════
        require(IERC20(loanToken).transfer(BALANCER_VAULT, repayment), "REPAY_FAILED");

        // ═══════════════════════════════════════════════════════════════
        // SEND PROFIT TO INITIATOR
        // ═══════════════════════════════════════════════════════════════
        require(IERC20(loanToken).transfer(initiator, profit), "TRANSFER_FAILED");

        emit Profit(profit, gasleft());
    }

    /// @notice Override amountIn in an exactInputSingle calldata payload.
    /// @dev Layout (no struct offset): selector(4) tokenIn(32) tokenOut(32)
    ///      fee(32) recipient(32) amountIn(32) ...
    ///      => amountIn occupies bytes [132..164) of the calldata content,
    ///      which starts at `add(legData, 32)`. So add(32, 132) = 164.
    function _overrideAmountIn(bytes memory legData, uint256 newAmountIn) internal pure returns (bytes memory) {
        assembly {
            mstore(add(legData, 164), newAmountIn)
        }
        return legData;
    }

    function rescueToken(address token, uint256 amount) external onlyOwner {
        (bool success,) = token.call(abi.encodeWithSelector(IERC20.transfer.selector, owner, amount));
        require(success, "TRANSFER_FAILED");
    }

    function rescueETH() external onlyOwner {
        (bool success,) = owner.call{value: address(this).balance}("");
        require(success, "ETH_TRANSFER_FAILED");
    }

    /// @notice Validates and decodes Leg 1 calldata
    /// @dev Ensures: SwapRouter02 struct selector (0x04e45aaf), loanToken as input,
    ///      amountIn == loanAmount, recipient == this contract, non-zero slippage guard,
    ///      and expected pool matches the supplied pool from factory.
    /// @return leg1OutputToken The token Leg 1 outputs (Leg 2 must accept it)
    function _validateAndDecodeLeg1(bytes memory legData, address loanToken, uint256 loanAmount, address legPool)
        internal
        view
        returns (address leg1OutputToken)
    {
        require(legData.length == 228, "LEG1_BAD_LENGTH");

        bytes4 selector;
        assembly { selector := mload(add(legData, 32)) }
        require(selector == bytes4(0x04e45aaf), "LEG1_BAD_SELECTOR");

        // tokenIn at offset 4 of calldata (add(legData, 36))
        address tokenIn;
        assembly { tokenIn := mload(add(legData, 36)) }
        require(tokenIn == loanToken, "LEG1_BAD_TOKEN_IN");

        // tokenOut at offset 36 of calldata (add(legData, 68))
        assembly { leg1OutputToken := mload(add(legData, 68)) }
        require(leg1OutputToken != address(0), "LEG1_ZERO_TOKEN_OUT");

        // fee at offset 68 of calldata (add(legData, 100))
        uint24 fee;
        assembly { fee := mload(add(legData, 100)) }

        // recipient at offset 100 of calldata (add(legData, 132))
        address recipient;
        assembly { recipient := mload(add(legData, 132)) }
        require(recipient == address(this), "LEG1_BAD_RECIPIENT");

        // amountIn at offset 132 of calldata (add(legData, 164)) — must match the loan amount
        uint256 amountIn;
        assembly { amountIn := mload(add(legData, 164)) }
        require(amountIn == loanAmount, "LEG1_BAD_AMOUNT_IN");

        // amountOutMinimum at offset 164 of calldata (add(legData, 196)) — must be non-zero
        uint256 amountOutMin;
        assembly { amountOutMin := mload(add(legData, 196)) }
        require(amountOutMin > 0, "LEG1_NO_SLIPPAGE_GUARD");

        // Validate on-chain pool against Uniswap V3 Factory
        address expectedPool = IUniswapV3Factory(UNISWAP_V3_FACTORY).getPool(tokenIn, leg1OutputToken, fee);
        require(expectedPool == legPool, "LEG1_INVALID_POOL");
        require(expectedPool != address(0), "LEG1_POOL_NOT_EXIST");
    }

    /// @notice Validates and decodes Leg 2 calldata
    /// @dev amountIn for leg2 is overridden on-chain to the real
    ///      intermediate balance, so it is NOT validated here.
    function _validateAndDecodeLeg2(bytes memory legData, address leg1OutputToken, address legPool) internal view {
        require(legData.length == 228, "LEG2_BAD_LENGTH");

        bytes4 selector;
        assembly { selector := mload(add(legData, 32)) }
        require(selector == bytes4(0x04e45aaf), "LEG2_BAD_SELECTOR");

        // tokenIn at offset 4 of calldata (add(legData, 36))
        address tokenIn;
        assembly { tokenIn := mload(add(legData, 36)) }
        require(tokenIn == leg1OutputToken, "LEG2_BAD_TOKEN_IN");

        // tokenOut at offset 36 of calldata (add(legData, 68))
        address tokenOut;
        assembly { tokenOut := mload(add(legData, 68)) }
        require(tokenOut != address(0), "LEG2_ZERO_TOKEN_OUT");

        // fee at offset 68 of calldata (add(legData, 100))
        uint24 fee;
        assembly { fee := mload(add(legData, 100)) }

        // recipient at offset 100 of calldata (add(legData, 132))
        address recipient;
        assembly { recipient := mload(add(legData, 132)) }
        require(recipient == address(this), "LEG2_BAD_RECIPIENT");

        // amountOutMinimum at offset 164 of calldata (add(legData, 196)) — must be non-zero
        uint256 amountOutMin;
        assembly { amountOutMin := mload(add(legData, 196)) }
        require(amountOutMin > 0, "LEG2_NO_SLIPPAGE_GUARD");

        // Validate on-chain pool against Uniswap V3 Factory
        address expectedPool = IUniswapV3Factory(UNISWAP_V3_FACTORY).getPool(tokenIn, tokenOut, fee);
        require(expectedPool == legPool, "LEG2_INVALID_POOL");
        require(expectedPool != address(0), "LEG2_POOL_NOT_EXIST");
    }

    /// @dev Returns this contract's balance of `token` (view helper so the
    ///      validators can enforce amountIn == loanAmount for leg1).
    function loanTokenBalance(address token) internal view returns (uint256) {
        return IERC20(token).balanceOf(address(this));
    }

    function _getRevertReason(bytes memory data) internal pure returns (string memory) {
        if (data.length == 0) return "REVERT";
        if (data.length < 68) return "REVERT_SHORT";
        assembly {
            data := add(data, 4)
            let returndata_size := sub(mload(data), 32)
            data := add(data, 32)
            if gt(returndata_size, 32) { returndata_size := 32 }
            returndatacopy(0, data, returndata_size)
            revert(0, add(returndata_size, 32))
        }
    }
}

interface IERC20 {
    function balanceOf(address) external view returns (uint256);
    function transfer(address, uint256) external returns (bool);
    function approve(address, uint256) external returns (bool);
}
